name: flamekit
description: "Bilibili Music Player"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.4.1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  qr_flutter: ^4.1.0
  cached_network_image: ^3.3.1
  encrypt: ^5.0.3
  pointycastle: ^3.7.4
  get_storage: ^2.1.1
  crypto: ^3.0.3
  uuid: ^4.3.3
  path_provider: ^2.1.2
  webview_flutter: ^4.7.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
